palette = "catppuccin_mocha"

format = """
[ î‚¶](peach)\
$os\
$username\
[î‚°](bg:surface1 fg:peach)\
$directory\
[î‚°](fg:surface1 bg:surface0)\
$git_branch\
$git_status\
[î‚°](fg:surface0 bg:base)\
$c\
$deno\
$golang\
$haskell\
$lua\
$nodejs\
$python\
$rust\
$zig\
[î‚°](fg:base bg:mantle)\
$time\
[î‚´](mantle) \
[ï„… ](bold peach)
"""

[character]
success_symbol = '[î˜¿](bold green) '
error_symbol = '[ï€](bold red) '

[username]
show_always = true
style_user = "bg:peach bold fg:crust"
style_root = "bg:peach bold fg:crust"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:peach fg:crust"
disabled = false

[os.symbols]
Arch = "ó°£‡ "

[directory]
style = "bg:surface1 fg:peach"
format = "[ $path ]($style)"
home_symbol = "ï€•"
truncation_length = 6
truncation_symbol = "../"


[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"
"rust" = "î¨"
"deno" = "ğŸ¦•"
"go" = "î˜§"
"c++" = "î˜"
"python" = "îœ¼"

[git_branch]
symbol = "ï˜"
style = "bg:surface0 fg:peach"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:surface0 fg:peach"
format = '[$all_status$ahead_behind]($style)'

[c]
symbol = "î˜"
style = "bg:base fg:yellow"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = "î˜ "
style = "bg:base fg:yellow"
format = '[ $symbol ($version)]($style)'

[deno]
symbol = "ğŸ¦•"
style = "bg:base fg:yellow"
format = "[ $symbol ($version)]($style)"

[golang]
symbol = "î˜§"
style = "bg:base fg:yellow"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î·"
style = "bg:base fg:yellow"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:base fg:yellow"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "îœ¼"
style = "bg:base fg:yellow"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:base fg:yellow"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:mantle"
format = '[ â™¥ $time ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

